# Generated by Django 3.2.5 on 2021-07-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('popularity', models.CharField(max_length=5, null=True)),
                ('imdbscore', models.CharField(max_length=5, null=True)),
                ('director', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('awards', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Adventure', 'Adventure'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Musical', 'Musical'), ('Animation', 'Animation'), ('Romance', 'Romance'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Horror', 'Horror')], max_length=255, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='imdbapi.movie')),
            ],
        ),
    ]
